/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./components/icons/IconHistory copy 2.vue')['default']
    3: typeof import('./components/icons/IconHistory copy 3.vue')['default']
    4: typeof import('./components/icons/IconHistory copy 4.vue')['default']
    5: typeof import('./components/icons/IconLike.vue')['default']
    ChatRoom: typeof import('./components/basic/ChatRoom.vue')['default']
    Comment: typeof import('./components/basic/Comment.vue')['default']
    copy: typeof import('./components/LiveHead copy.vue')['default']
    Dialog: typeof import('./components/Dialog.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HistoryItem: typeof import('./components/basic/HistoryItem.vue')['default']
    Icon: typeof import('./components/icons/Icon.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconFriends: typeof import('./components/icons/IconFriends.vue')['default']
    IconHistory: typeof import('./components/icons/IconHistory.vue')['default']
    IconLike: typeof import('./components/icons/IconLike.vue')['default']
    IconMessage: typeof import('./components/icons/IconMessage.vue')['default']
    IconSearch: typeof import('./components/icons/IconSearch.vue')['default']
    IconSubscribe: typeof import('./components/icons/IconSubscribe.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    LiveAbout: typeof import('./components/LiveAbout.vue')['default']
    LiveAudience: typeof import('./components/LiveAudience.vue')['default']
    LiveDialog: typeof import('./components/LiveDialog.vue')['default']
    LiveFooter: typeof import('./components/LiveFooter.vue')['default']
    LiveHead: typeof import('./components/LiveHead.vue')['default']
    LiveHost: typeof import('./views/PeerLiveHost.vue')['default']
    LiveIndex: typeof import('./views/PeerLiveIndex.vue')['default']
    LiveInfo: typeof import('./components/LiveInfo.vue')['default']
    LiveRoom: typeof import('./components/LiveRoom.vue')['default']
    LiveSetting: typeof import('./components/LiveSetting.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StreamSource: typeof import('./components/StreamSource.vue')['default']
    TempCodeRunnerFile: typeof import('./components/tempCodeRunnerFile.vue')['default']
    VideoPlayer: typeof import('./components/basic/VideoPlayer.vue')['default']
  }
}
